name: Publish

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  generic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: "20"

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 9.12.3
          run_install: false

      - name: login to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > ~/.npmrc
          git config --global user.name "ariesclark"
          npm whoami
      - name: install dependencies
        run: pnpm i --shamefully-hoist

      - name: build package
        run: pnpm build

      - name: publish package
        run: pnpm publish --no-git-checks --access public
